=== subeesh673571/iiitkottayam/src/data/_schema/btech_students.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "src/data/btech_students.json",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "_help": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Notes for whoever edits this file. Ignored when the site is built."
    },
    "b15": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b16": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b17": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b18": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b19": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b20cse": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b20ec": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== subeesh673571/iiitkottayam/src/data/btech_students.json
{
  "$schema": "./_schema/btech_students.json",
  "_help": [
    "btech students grouped by admission batch.",
    "Each key (b19, b20, ...) becomes one tab; the list under it is the names.",
    "Add a new batch by copying a block and giving it the next key."
  ],
  "b15": [
    "A. ADDEPALLI VENKATA MANIKYALA RAO",
    "AKASH TIMMAPURAM",
    "ANIL KUMAR YADAV",
    "ANJU MARY PETER",
    "ANUJ BHATLA",
    "BANAVATH SHIVA SHANTHA MANI",
    "BEVARA RAVI VARMA KUMAR",
    "DARLA PRASHANTH",
    "ESLAVATH RAMYA",
    "ETHAKOTA PAVANSAI",
    "HARSH KUMAR SINGH",
    "JALIBILI PUSHPAK",
    "KALIDINDI ALEKHYA",
    "KODURU JASWANTH KUMAR",
    "KOTLAPUDI JASWANTH",
    "KOYYANA YASHWANT SRIVATSAV",
    "MAROTU RAJESH KUMAR",
    "MEDA RAVALI",
    "MOOD DINESH",
    "MUNJULURI SRIJA ASRITHA",
    "POSIPOGU ANANDA BHARATH",
    "RAJAT KUMAR",
    "SAVIO JOSE",
    "SHIVENDRA SINGH",
    "SHUBHAM KUMAR",
    "SUMALA SAI SIDDARDHA",
    "VANKUDOTH PREMKUMAR",
    "VEERANALA SANDEEP KUMAR",
    "VEMULAPALLI RAJESH",
    "JUHAL SIBY"
  ],
  "b16": [
    "A. VANSHIKHA JAIN",
    "ABHISHEK KUMAR",
    "AKASH PUNDIR",
    "AMRITHA HARIDASAN",
    "AMRUTHAM ABHINAV",
    "ANKIT VERMA",
    "ARJUN M.",
    "AVULA PRAVEEN",
    "CHATALA AKHILESWARA KUMAR",
    "DETI PRUDVI",
    "DHULIPALLA SAHIL TEJA",
    "GUGULOTHU ESHWAR SAI",
    "JONNADA SAI MADHAV",
    "KAMBLE CHARUDATTA DAYANAND",
    "KELAVATH JAISINGH",
    "KOCHUTHARAYIL PHILIP",
    "KOPPETI DANIEL KAMAL RAJ",
    "MADDIRALLA VINAY KUMAR",
    "MANNEM SRINIVAS",
    "SIDDHARTH MAURYA",
    "NALLAPATI LAKSHMI VARA VENKATA SAI",
    "PAMULA GAYATHRI",
    "SAHUKARI OMSAI CHOWDARY",
    "SAI SURYA KIRAN POKALA",
    "SAMEER KUMAR SATYADARSHI",
    "THALARI RAVINDRA",
    "VISHNU S.",
    "YEDLA SANDEEP KUMAR",
    "BANOTHU UTTAM NAIK",
    "PRASANNA KUMAR YAGATHI"
  ],
  "b17": [
    "AADITHYA RAJ R.",
    "ABHISHEK VISHWAKARMA",
    "ADHYAN",
    "ADITYA KUMAR NAYAK",
    "ALLU HARSHAVARDHAN",
    "ANKIT ANAND",
    "ANSHUMAN GAURAV",
    "ANSHUMAN MISHRA",
    "ANUJ SRIVASTAVA",
    "ARINDAM SINGH SENGAR",
    "ARVIND RAJPUROHIT",
    "ASHISH GUSAIN",
    "AYUSH RAI",
    "BANAVATH JYOTHIKA",
    "DEEPESH SHARMA",
    "DEVARAKONDA SRI VISHNU TEJA",
    "DHARAVATHU NEEHARI NAIK",
    "GARVIT SHARMA",
    "GAURAV KANWAT",
    "GONDU SHIVAKRISHNA",
    "GORINKA RITHIKA",
    "GUNISH",
    "GUNJAN ASIT BAGDE",
    "J. SANGEETHA",
    "JAINEEL FENAL DHARIA",
    "JANGAMREDDY HARSHA VARDHAN REDDY",
    "JOEL MATHEW PHILIP",
    "KARTHIKAYINI A",
    "KONIDANA SAI MANOJ",
    "KONJETY KEERTHI SREENIVAS",
    "KOTA MANOJ KUMAR",
    "KSHITIJ PAL",
    "LAVANYA S.",
    "LOVE KUMAR",
    "MADIPADIGE LAXMAN",
    "MAHFUZ HASAN",
    "MAREPALLY SHIVAKUMAR",
    "MATTAPARTI SATYA BHARGAVI",
    "MEKALA UDAY BHARGAV",
    "NEERAJ SAJEEV NAIR",
    "PATTAN SALIM KHAN",
    "PRAJNA VARIJ REDDY SARELLA",
    "RAHUL KUMAR SINGH",
    "REDDEDDY ANURAG REDDY",
    "RISHAV JAISWAL",
    "ROHITH SEBY",
    "S. J. SAMEER AHMED",
    "S. RAHUL BADAMI",
    "SAGAR BHATIA",
    "SANGEETHA SURESH",
    "SANTOSH SHARMA",
    "SATYAM RAJ",
    "SHUBHAM MISHRA",
    "SHUBHAM VINOD KHAMITKAR",
    "SOMESH KUMAR",
    "SRILAKSHMI AJITH",
    "SUDHANSHU",
    "SURYAPAL SINGH ASOLIA RAO",
    "TUMUN SHAILY",
    "UTKARSH TRIVEDI",
    "VANGAPANDU SANDEEP",
    "VEDANT SANDEEP JOSHI",
    "VIBHOR VIJ",
    "VISHAL SHIVAKUMAR KANAKAMAMIDI",
    "VISHNU KHANTH BASKARAN"
  ],
  "b18": [
    "A V BHAVYA",
    "A V S ADITYAVARDHAN",
    "AELLIPEDDI SINDHUR ANJUMAN TEJ",
    "AMEYA GUPTA",
    "ANANTHU RAGHUVAMSI",
    "ANJALI M N",
    "ANTONY FRANCIS",
    "BHASKAR PUROHIT",
    "BIVEK BENOY PAUL",
    "BUSIREDDY MANSI REDDY",
    "CHINTHA OMESH SAI",
    "DEVARANENI DINESH",
    "DHANUSH R H",
    "DHURJATI VATS",
    "DINESH KUMAR P",
    "ESLAVATH PAVAN",
    "GUDI AVINASH",
    "GUMMADI AVINASH",
    "HARIPRASATH K",
    "JAGRITI THAKUR",
    "JONNALAGADDA VENKATA SATHYA KRISHNA",
    "KANDULA VENKATESHWAR REDDY",
    "KARTHIK B S",
    "KAUSHAL",
    "KAUSHAL SAMANT",
    "KODALI SIVA GANESH",
    "KOTHAPALLE SHYAM SUNDAR",
    "KUMARI MISA",
    "KUSHAGRA MANISH",
    "M G CHRISTOPHER",
    "MACHARLA SINDHUJA",
    "MADALA NIRUPAMA CHOWDARY",
    "MADDA AISHWARYA",
    "MAHESH M",
    "MEENAKSHI VENKITTARAMAN",
    "MEESALA SOWMYA",
    "MUHAMMED NIHAL K V",
    "MUHAMMED NIZAR E",
    "MUSKAN RANA",
    "NIKHIL KUMAR",
    "NIKHIL KUMAR GHANGHOR",
    "PADIYA SURENDAR",
    "PAMARTHI KUNAL",
    "PASUMARTHI ABHISHEK",
    "PASUPULETI SAI KUMAR",
    "PEDADA VENKATA HARSHA",
    "PEDDI SHWEJAN",
    "PRABAL KALIA",
    "PRABHAV KUMAR SINGH",
    "PUSHPAM SAXENA",
    "RACHIT VERMA",
    "RAGHUL MANI R S",
    "RAGURAAM D",
    "RAHUL NAYAK B V",
    "RAHUL RANJAN",
    "RAMANA BOYANA GOVARDHAN",
    "RAMKUMAR",
    "RITIK NIRAJ AGRAWAL",
    "ROSHINI RASHEED",
    "RUCHIKA SREEDHAR",
    "RUMAISE",
    "S SREEVASASUDHARSAN",
    "SAARUN P NAIR",
    "SAI KUMAR AVU",
    "SAMUDRALA SHIVA KUMAR",
    "SARFARAZ AHMED K L",
    "SHIVANSH DARSHAN",
    "SHREYAS J S",
    "SIDDHARTH ASHOK UNNITHAN",
    "SNEHAMOL BALAN",
    "SREENIVASA SUMADITHYA",
    "SUMANA BUSHI REDDY",
    "TARUN KUMAR SINGH",
    "TEJASH MORE",
    "TIJO THOMAS",
    "UPPILI SANDEEP",
    "VAISAKH DILEEP",
    "VENKATASWAMY SUNDAR",
    "VISHNU AJITH",
    "YADDANAPUDI VINAY",
    "YAMPARALA VENKATA GOPI",
    "YARLAGADDA SAI BHAVADEESH",
    "ALLU HARSHAVARDHAN"
  ],
  "b19": [
    "ADITYA TAPARIA",
    "CYRIL KUNJUMON",
    "SRI RAMA VARSHITH POTHARLANKA",
    "SOM SAGAR",
    "ANCHITA ARORA",
    "VENATI PRUDHVI REDDY",
    "ASHWIN NAIR",
    "SESHATHRI S",
    "POTHARAJU BHARGAWA",
    "RISHABH ANAND",
    "CHANDRIMA MELOTH JAYARAM",
    "ABHIJITH S BABU",
    "NISHANT KUMAR",
    "VISHNU NARAYANAN A",
    "CHARLES V.J.",
    "MECHARLAVANDANA",
    "VELLATURI VENKATA SAI KOWSIK",
    "KUMBHAR ABHIMANYU CHHOTELAL",
    "ANSHU KUMAR",
    "JASHAN PURI",
    "JEET SHAH",
    "RINGRIANGSUIYANG",
    "CHANDRAHAS REDDY GURRAM",
    "SHASHANK SINGH",
    "LAKSHIN KUMAR R",
    "TANISHQ JAIN",
    "SRIVATSAN H",
    "DUNGA HEMANTH BHARADWAJ",
    "VANAM MAHESH",
    "JEETESH GAVANDE",
    "BOLGAM KATHYAYANI",
    "SHIVAM KUMAR CHAUDHARY",
    "PRIYANSHU  GUPTA",
    "THIPPANAPALLI HITEESH",
    "BHIDE SHRIGANESH SHASHANK",
    "DHEENADHAYALAN R",
    "ADDANKI DHANUSH VENKAT",
    "DESHABOINA YASHWANTH",
    "AMAN VERMA",
    "ALWIN SEBASTIAN",
    "NIMIT GAUR",
    "ALAKA JAYAN CHOORAPPETTY",
    "AASHISH SHARMA",
    "NEVIN JOHN SELBY",
    "NAGIREDDYGARI NAGAVARDHAN REDDY",
    "BANDE AKHIL SAI",
    "DHANUSH BINU",
    "KUMAR SUNNY",
    "BHANU KRISHNA PRASAD VIPPARLA",
    "ANANTHAKRISHNAN N B",
    "VAISAKH N P",
    "SHINDE SOHAM SANTOSH",
    "YELLANTI NITHISH CHOWDARY",
    "SWANI SUNDARA DIDDE",
    "BERI BHANU VISHNU VARDHAN REDDY",
    " PATHI VEDAVRATH",
    "JANGAM ANURAG",
    "PARLAPALLI HEMANTH KUMAR REDDY",
    "ADITYA MUTHARIA",
    "TEEPARTI TEJ AKASH",
    "KANCHARLA THOLI KIRAN",
    "MARGANI ROHITH",
    "HRISHABH JOSHI",
    "VISHNU S",
    "SALEMULA SHAREEF",
    "PENUGONDA SATWIKA",
    "PARTHA PRATIM BISWAS",
    "PAKANATI VARUN REDDY",
    "MOJALA CHARIT VINAY",
    "SADDIKUTI VISHNU VARDHAN REDDY",
    "HISANA MOHAMMED BASHEER",
    "SYED FAIZ HASAN",
    "ANOOP RAJU",
    "GAMIDI SURYA PAVAN",
    "SHAIK LUCKMAN LAL MIYA BAHADUR",
    "BELLAM VENKATA SURYA ASHISH",
    "PIYUSH BANSAL",
    "SUSHANT KUMAR DAS",
    "PANDEY SHUBHAM OMPRAKASH",
    "LAKAVATH YASHWANTH",
    "POKALA PRAMODH REDDY",
    "MALOTH YASHWANTH NAIK",
    "KURUVA SAI NRUTHIK SRI HARSHA",
    "PRASANNA JAGADEESH DEVADIGA",
    "INDIREDDY TRISHAL REDDY",
    "ANNABATHULA NITHIN",
    "AMAN SAHU",
    "ESLAVATH.DILEEP",
    "K RAGHUVAMSHI",
    "KANDLAGUNTA PRADEEP KUMAR",
    "TAMALAMPUDI SRICHARAN REDDY",
    "PARUCHURI SAI SUHAS",
    "KODIVENDLA ABHISEKHAR",
    "CHADIPIRALLA JASWANTH REDDY",
    "KISHORE PRASAD N",
    "POLU AMRUTHA",
    "PALLAVOLU JASWANTH",
    "YADAV ARYAN LALCHANDRA",
    "NALLAMOTHU SAI CHANDU",
    "MODASSIR ANSARI",
    "SAI  TEJASHWIN ESWARAPU",
    "ABHISHEK H PATIL",
    "GAJJALA RITHISH KUMAR REDDY",
    "KOVVADA HARSHA VARDHAN",
    "AGIRISHETTY KISHORE",
    "MUDAVATH SAI TEJA",
    "RODRIGUES JOSHI PAUL",
    "BEERAKA HRITHIK",
    "KALIGITHI PRANAI RAJ",
    "VAJRAPU SUGNAN KRANTHI RAJU",
    "NIKHIL JANA",
    "HARSH GUPTA",
    "KOTTANA GNANESWARA RAO",
    "LOKESH RAI",
    " MODI TAMBOLI SOHEL SAMIRKHAN",
    "RUPESH DANGI"
  ],
  "b20cse": [
    "ANAGHA N",
    "APPUS DEVIS K",
    "SHAIK MOHAMMAD FAHAD",
    "IRISH.K.SAJAN",
    "VIPUL KHANDKE",
    "DERICK SEN",
    "VISHWESH ANANTHA KRISHNAN",
    "ADITYA SRINIVAS MENON",
    "SRIHITH PRUDHIVI",
    "KOTIKALAPUDI SUMANTH",
    "EENADULA BHANUPRAKASH",
    "VATSAL SINHA",
    "SUYASH SINGH CHAUHAN",
    "SODAGUM SANKALP",
    "SHASHANK KUMAR SRIVASTAVA",
    "NIKHIL MENON",
    "HEGDE KARTHIK MOHAN",
    "IBRAHIM AHMED KHAN",
    "ROSHIN NISHAD",
    "ASHUTOSH RAI",
    "MERCHANTABDULLAH MOHAMED",
    "SUJAL SABAVAT",
    "LEO TOM",
    "SYAM SIVADAS",
    "YEGGONI NAGA MURALIDHAR REDDY",
    "KRISHNA SASHANK ALLIMPALLI",
    "ROSHINI P",
    "NEVLIN THEKKETATH NOBLE",
    "ASHWANI KUMAR JHA",
    "DOMMATI MANIKANTA",
    "JOEL M TOM",
    "ALURU HEMA SUNDHER",
    "BURRI VENKATA SHASHANK REDDY",
    "ANKUR KUMAR MANDAL",
    "GUNDLAPALLI SANDEEP",
    "THIRDHAKSHAR SAI GHANTA",
    "ADHITHYA SANKAR",
    "MOHAMMED ZIYAD CHEERAMTHODIKA",
    "PRAJJWAL MAHARUDRA JOGDAND",
    "BARANIDARAN M",
    "PRANJAL PRASOON",
    "BHUSHI TAGORE SUBBBARAI",
    "ERUKALA CHARAN TEJA",
    "KAPPAGANTHU BRAHMARAMBHIKA JYOTHI",
    "ADVAITH ANIL",
    "SANGAM VIVEK REDDY",
    "I. KAVYA SRAVANI",
    "NITHISH KUMAR R ",
    "MAJJI SAI VAMSI",
    "NABEEL AHMED KHAN",
    "SHAUN VARGHESE",
    "ANOUSHKA SUDHIR ",
    "KHUSHWANT SINGH",
    "ISHAAN MAHESH",
    "SARTHAK BINDAL",
    "NAGARAM JOELRAJ",
    "PALASH ARUN RAWAT",
    "SAAD RAHMAN WARSI",
